[[redirects]]
  from = "/proxy/*"
  to = "https://dapi.kakao.com/:splat"
  status = 200
  force = true
  headers = { Authorization = `KakaoAK ${process.env.REACT_APP_KAKAO_API_KEY}` }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200