# SPA router support.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# api redirect.
[[redirects]]
  from = "/api/*"
  to = "https://dapi.kakao.com/:splat"
  status = 200
  headers = { Access-Control-Allow-Origin = “*”, Authorization = “Bearer api-key”}
  force = true