[[redirects]]
  from = "/api/search-address"
  to = "/.netlify/functions/kakaoSearch"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  functions = "netlify/functions"